name: CI

on: [push, pull_request]

jobs:


    buildDebug:
        name: Debug build
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            -   name: Run release build
                run: ./gradlew assembleRelease

            -   name: Upload artifact to GitHub
                uses: actions/upload-artifact@v2
                with:
                    name: Fdroid-debug.apk
                    path: ./app/build/outputs/apk/basic/debug/app-basic-debug.apk
